### PR TITLE
Chore/update latest rascal release

### PR DESCRIPTION
**Pull request by rodinaarssen**
Updated to
* `rascal`: 0.40.17
* `rascal-maven-plugin`: 0.28.9

The updated type checker identified some issues:
* Code clone 1 (which I [removed](c731909031dfb0b77ee87ac584c33c9a3814d12b))
* "Code clone" 2: two functions with identical signature and name, but different implementation. There were no call sites; I [removed them both](fc7b70c30d3f41c624df486dbfc1a902c8c2c638).
* [Fixed](f1b3a08a2392f7e9d2f119e3f668231eff6dc4ad) a constructor name

### CODE REVIEW

**Comment by jurgenvinju** [comment]
@mahills could you have a quick look at these changes. I may have accepted them without too much scrutiny and merged in the interest of the Rascal release. Rodin was asking for a peek by us. Much obliged!

**Comment by mahills** [comment]
I'll take a look, but it may take a couple of days.

**Comment by mahills** [comment]
The one to remove a doubly-defined function is fine. I'm guessing code got merged in there from another module. That module honestly was a bit of a mess and needed some serious refactoring anyway. I think those functions were just sanity checks added while that module was being built -- it was part of the code for the ISSTA 2013 paper, but that is actually hosted here: [https://github.com/PLSE-Lab/issta-2013](https://github.com/PLSE-Lab/issta-2013)

**Comment by mahills** [comment]
The commit to fix the constructor name is also fine. It had been named `use` at one point, but was renamed to split the info out into a new data type with a `use` constructor.

**Comment by mahills** [comment]
For the commit to remove a code clone, the three functions do different things, but were written in a lazy way (by me) and could be written in a better way using an optional filter. I don't _think_ these were being used, but may have appeared in older code repos that were made available as artifacts for papers. If we need these, we can put them back. We aren't really tracking stats like this anymore since this required manually updating a spreadsheet, now we extract them automatically (and don't include the PHP version number, which required manual inspection), so we won't miss these going forwards.

**Comment by mahills** [comment]
Okay, so I think that's all of them, I got curious so I just looked now, but if I need to look at something else please let me know!

**Pull request merged**
